name: "CI - Test Templates"
on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changed templates
        run: |
          make detect-changes
        id: detect_changes

    outputs:
      templates: ${{ steps.detect_changes.outputs.templates }}

  test:
    needs: detect-changes
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: make install-dependencies

      - name: Build templates
        run: make build TEMPLATE=${{ matrix.templates }}

      - name: Run tests
        run: make test TEMPLATE=${{ matrix.templates }}